### ISSUE TITLE
using Username+Password

### ISSUE THREAD

**Issue by MrOplus** [AnhTVc/OpenConnectIOS#1]
hi , 
in this project you've just asked for username only , but most servers are working with username+password 
how can i provide the password (i'm not familiar with Obj-c) 

in log section i've got  : 
```
POST HTTPS://IP
Attemping to connecto to server ip:443
SSL negotiation with ip
server certificate verify failed: unable to get local issuer certificate
Connected to https on ip 
xml post enabled 
please enter your username
POST https://ip/auth
please enter your password. 
Post https://ip/auth
got response : http/1.1 503 service unavailable 
```

**Comment by AnhTVc** [comment]
view in class: Wrapper
Please contact me by email to see your issue

**Comment by FazilMuhammed** [comment]
@AnhTVc  I have too same issue can you help me. I need wrapper with username and password

**Comment by FazilMuhammed** [comment]
@kooroshh can solve the issue?

**Comment by MrOplus** [comment]
> @kooroshh can solve the issue?

nope i've left this repo behind

**Comment by AnhTVc** [comment]
hi all, this issue fixed. Pls connect with me by skype get source code
skype id: tranvietanh.hust@gmail.com

**Comment by brettwooldridge** [comment]
Again, this is GitHub, why should we have to contact you via Skype to get “the full source code “?
